=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Listin/listin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:simpleType name="restriccion_identificador">
    <xs:restriction base="xs:ID">
      <xs:pattern value="([a-za-z]*)"/>
      <xs:maxLength value="8"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="restriccion_sexo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="hombre"/>
      <xs:enumeration value="mujer"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="restriccion_relacion">
    <xs:restriction base="xs:IDREF">
      <xs:pattern value="([a-za-z]*)"/>
      <xs:maxLength value="8"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="listin" type="tipo_listin"/>
  
  <xs:complexType name="tipo_listin">
    <xs:sequence>
      <xs:element name="persona" type="tipo_persona" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipo_persona">
    <xs:sequence>
      <xs:element name="nombre" minOccurs="1" maxOccurs="1" type="xs:string"/>
      <xs:element name="email" minOccurs="0" maxOccurs="2" type="xs:string"/>
      <xs:element name="relacion" minOccurs="0" maxOccurs="1" type="tipo_relacion"/>
    </xs:sequence>
    <xs:attribute name="id" type="restriccion_identificador" use="required"/>
    <xs:attribute name="sexo" type="restriccion_sexo" use="optional"/>
  </xs:complexType>
  
  <xs:complexType name="tipo_relacion">
    <xs:attribute name="enemigo_de" type="restriccion_relacion"/>
    <xs:attribute name="amigo_de" type="restriccion_relacion"/>
  </xs:complexType>
  
</xs:schema>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Soluciones/01_listin/listin.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<listin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="listin.xsd">

    <persona id="mgarciad" sexo="hombre">
        <nombre>Marcos</nombre>
        <email>mgarciadegodos@egibide.org</email>
        <relacion enemigo_de="earbailz" amigo_de="mgarciad"/>
    </persona>

    <persona id="earbailz" sexo="mujer">
        <nombre>Eider</nombre>
        <email>earbailza@egibide.org</email>
        <relacion amigo_de="mgarciad"/>
    </persona>

</listin>
