=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Soluciones/02_agenda/agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="agenda" type="tipo_agenda"/>

  <xs:complexType name="tipo_agenda">
    <xs:sequence>
      <xs:element name="contacto" type="tipo_contacto"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipo_contacto">
    <xs:sequence>
      <xs:element name="Nombre" type="xs:string"/>
      <xs:element name="Direccion" type="xs:string"/>
      <xs:element name="Ciudad" type="xs:string"/>
      <xs:element name="Provincia" type="xs:string"/>
      <xs:element name="Codigo_Postal" type="xs:int"/>
      <xs:element name="Numeros" type="tipo_numeros"/>
      <xs:element name="Email" type="xs:string"/>
      <xs:element name="Web" type="xs:string"/>
      <xs:element name="Compania" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipo_numeros">
    <xs:sequence>
      <xs:element name="Telefono" type="xs:int"/>
      <xs:element name="Fax" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Soluciones/02_agenda/agenda.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="agenda.xsd">

    <contacto>
        <Nombre>Marcos</Nombre>
        <Direccion>Hurtado de Amezaga</Direccion>
        <Ciudad>Bilbao</Ciudad>
        <Provincia>Bizkaia</Provincia>
        <Codigo_Postal>48008</Codigo_Postal>
        <Numeros>
            <Telefono>944305879</Telefono>
            <Fax>945781122</Fax>
        </Numeros>
        <Email>mgarciadegodos@egibide.org</Email>
        <Web>www.egibide.org</Web>
        <Compania>Egibide</Compania>
    </contacto>
</agenda>
