=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Pedido/Pedido.dtd
<!ELEMENT pedido (fecha, cliente, producto*, envio)>
    <!ELEMENT fecha (dia, mes, anio)>
        <!ELEMENT dia (#PCDATA)>
        <!ELEMENT mes (#PCDATA)>
        <!ELEMENT anio (#PCDATA)>

<!ELEMENT cliente (nombre, apellido, direccion, ciudad, cod_postal)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT cod_postal (#PCDATA)>

<!ELEMENT producto (precio, cantidad)>
    <!ATTLIST producto
                cod ID #REQUIRED
                nomb CDATA #REQUIRED>
    <!ELEMENT precio (#PCDATA)>
        <!ATTLIST precio
                    moneda CDATA #IMPLIED>
    <!ELEMENT cantidad (#PCDATA)>

<!ELEMENT envio (nombre, apellido, direccion, ciudad, cod_postal)>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Pedido/Pedido.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pedido SYSTEM "Pedido.dtd">
<pedido>
    <fecha>
        <dia>20</dia>
        <mes>02</mes>
        <anio>2012</anio>
    </fecha>
    <cliente>
        <nombre>Ricardo</nombre>
        <apellido>Molina</apellido>
        <direccion>Avenida Gasteiz 56</direccion>
        <ciudad>Vitoria</ciudad>
        <cod_postal>01012</cod_postal>
    </cliente>
    <producto cod="_872-AA" nomb="cortadora">
        <precio>148,95</precio>
        <cantidad>1</cantidad>
    </producto>
    <producto cod="_926-FH" nomb="podadora">
        <precio moneda="euro">7,98</precio>
        <cantidad>3</cantidad>
    </producto>
    <envio>
        <nombre>Ines</nombre>
        <apellido>Abad</apellido>
        <direccion>Plaza de la Duquesa 12</direccion>
        <ciudad>Pamplona</ciudad>
        <cod_postal>31010</cod_postal>
    </envio>
</pedido>
