=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Simulacro Examen/Solución/Ejercicio 3/simulacro_examen_ej3.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--
        TrackingUpdateResponse.dtd
        Copyright (C) 2014, Shipwire Inc. All rights reserved.
        Last modified: 2014-05-04
        -->
        <!ELEMENT TrackingUpdateResponse (Status, Order*,
                TotalOrders, TotalShippedOrders, TotalProducts,
                ResultsLimit?, ResultsOffset?,
                Bookmark?, ProcessingTime?)>
        <!ELEMENT Status (#PCDATA)>
        <!ELEMENT Order (TrackingNumber*, Holds?, Items?, RelatedOrder*)>
        <!ATTLIST Order
                id CDATA #REQUIRED
                shipwireId CDATA #REQUIRED
                internalId CDATA #REQUIRED
                warehouse CDATA #IMPLIED
                shipped (YES|NO) #REQUIRED
                shipper CDATA #IMPLIED
                shipperFullName CDATA #IMPLIED
                shipDate CDATA #IMPLIED
                cancelDate CDATA #IMPLIED
                delivered (YES|NO|UNKNOWN) #IMPLIED
                expectedDeliveryDate CDATA #IMPLIED
                handling CDATA #IMPLIED
                shipping CDATA #IMPLIED
                packaging CDATA #IMPLIED
                insurance CDATA #IMPLIED
                total CDATA #IMPLIED
                returned (YES|NO) #REQUIRED
                returnDate CDATA #IMPLIED
                returnCondition (GOOD|BAD|MIXED) #IMPLIED
                href CDATA #IMPLIED
                affiliateStatus (shipwireFulfilled|canceled|held|merchantFulfilled|duplicate) #IMPLIED
                manuallyEdited (YES|NO) #IMPLIED
                >
        <!ELEMENT TrackingNumber (#PCDATA)>
        <!ATTLIST TrackingNumber
                carrier CDATA #REQUIRED
                delivered (YES|NO|UNKNOWN) #IMPLIED
                summary CDATA #IMPLIED
                summaryDate CDATA #IMPLIED
                deliveryDate CDATA #IMPLIED
                href CDATA #IMPLIED
                >
        <!ELEMENT Holds (Hold*)>
        <!ELEMENT Hold (Date, Type, Description)>
        <!ELEMENT Date (#PCDATA)>
        <!ELEMENT Type (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Items (Item*)>
        <!ELEMENT Item (Code, Quantity, UnitValue?, ItemData*)>
        <!ELEMENT Code (#PCDATA)>
        <!ELEMENT Quantity (#PCDATA)>

        <!ELEMENT UnitValue (#PCDATA)>
        <!ATTLIST UnitValue
                currency CDATA #IMPLIED
                >
        <!ELEMENT ItemData (#PCDATA)>
        <!ATTLIST ItemData
                type (serialNumber|lotNumber|other) #REQUIRED
                >
        <!ELEMENT RelatedOrder (TrackingNumber*)>
        <!ATTLIST RelatedOrder
                type (return|undershipment|overshipment|split|parent) #REQUIRED
                shipwireId CDATA #REQUIRED
                internalId CDATA #REQUIRED
                >
        <!ELEMENT TotalOrders (#PCDATA)>
        <!ELEMENT TotalShippedOrders (#PCDATA)>
        <!ELEMENT TotalProducts (#PCDATA)>
        <!ELEMENT ResultsLimit (#PCDATA)>
        <!ELEMENT ResultsOffset (#PCDATA)>
        <!ELEMENT Bookmark (#PCDATA)>
        <!ELEMENT ProcessingTime (#PCDATA)>
        <!ATTLIST ProcessingTime
                units CDATA #REQUIRED
                >

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Simulacro Examen/Solución/Ejercicio 3/simulacro_examen_ej3.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE TrackingUpdateResponse SYSTEM "../DTD/simulacro_examen_ej3.dtd">
<TrackingUpdateResponse>
    <Status>En transito</Status>
    <Order id="1" shipwireId="12" internalId="123" shipped="YES" returned="NO"
    warehouse="5" shipper="65" shipperFullName="Envios S.A." shipDate="05-10-2016"
    cancelDate="" delivered="NO" expectedDeliveryDate="7-10-2016" handling="care"
    shipping="boat" packaging="box" insurance="NO" total="3" returnDate=""
    returnCondition="GOOD" href="324" affiliateStatus="shipwireFulfilled" manuallyEdited="NO">
        <TrackingNumber carrier="343" delivered="NO" summary="" summaryDate="" deliveryDate="" href="324">
            789254687
        </TrackingNumber>
        <Holds>
            <Hold>
                <Date>06-10-2016</Date>
                <Type>aduana</Type>
                <Description>retencion en la aduana</Description>
            </Hold>
        </Holds>
        <Items>
            <Item>
                <Code>6543</Code>
                <Quantity>6</Quantity>
                <UnitValue currency="eur">50</UnitValue>
                <ItemData type="lotNumber">7855</ItemData>
            </Item>
        </Items>
        <RelatedOrder type="parent" shipwireId="2314" internalId="4324">
            <TrackingNumber carrier="343" delivered="NO" summary="" summaryDate="" deliveryDate="" href="324">
                789254686
            </TrackingNumber>
        </RelatedOrder>
    </Order>
    <TotalOrders>1</TotalOrders>
    <TotalShippedOrders>1</TotalShippedOrders>
    <TotalProducts>1</TotalProducts>
    <ResultsLimit>19</ResultsLimit>
    <ResultsOffset>15</ResultsOffset>
    <Bookmark>marcado</Bookmark>
    <ProcessingTime units="horas">8</ProcessingTime>
</TrackingUpdateResponse>
