=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Periodico/Periodico/Periodico.dtd
<!ELEMENT periodico (cabecera,portada,seccion+,contraportada)>

	<!ELEMENT cabecera (nombre,fecha,lugar,numero,precio)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT fecha (#PCDATA)>
		<!ELEMENT lugar (#PCDATA)>
		<!ELEMENT numero (#PCDATA)>
		<!ELEMENT precio (#PCDATA)>

	<!ELEMENT portada (titular,noticia+,publicidad*)>
		<!ELEMENT titular (#PCDATA)>
		<!ELEMENT publicidad (#PCDATA)>

	<!ELEMENT seccion (noticia+)>
	<!ATTLIST seccion tipo (internacional|opinion|nacional|cultura|deportes|tvradio) #REQUIRED>

		<!ELEMENT noticia (titulo,subtitulo,entradilla,cuerpo)>
			<!ELEMENT titulo (#PCDATA)>
			<!ELEMENT subtitulo (#PCDATA)>
			<!ELEMENT entradilla (#PCDATA)>
			<!ELEMENT cuerpo (#PCDATA)>

<!ELEMENT contraportada EMPTY>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Periodico/Periodico/Periodico.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE periodico SYSTEM "Periodico.dtd">
<periodico>
	<cabecera>
		<nombre></nombre>
		<fecha></fecha>
		<lugar></lugar>
		<numero></numero>
		<precio></precio>
	</cabecera>
	<portada>
		<titular></titular>
		<noticia>
			<titulo></titulo>
			<subtitulo></subtitulo>
			<entradilla></entradilla>
			<cuerpo></cuerpo>
		</noticia>
	</portada>
	<seccion tipo="">
		<noticia>
			<titulo></titulo>
			<subtitulo></subtitulo>
			<entradilla></entradilla>
			<cuerpo></cuerpo>
		</noticia>
	</seccion>
	<contraportada/>
</periodico>
