=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Agenda/agenda.dtd
<!ELEMENT agenda (nombre, direccion, ciudad, provincia, cod_postal, numeros, email, web, compania)>

        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT provincia (#PCDATA)>
        <!ELEMENT cod_postal (#PCDATA)>
        <!ELEMENT numeros (telefono, fax)>
            <!ELEMENT telefono (#PCDATA)>
            <!ELEMENT fax (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT web (#PCDATA)>
        <!ELEMENT compania (#PCDATA)>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Agenda/agenda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <nombre>Marcos</nombre>
    <direccion>Hurtado de Amezaga</direccion>
    <ciudad>Bilbao</ciudad>
    <provincia>Bizkaia</provincia>
    <cod_postal>48008</cod_postal>
    <numeros>
        <telefono>344448578</telefono>
        <fax>654521478</fax>
    </numeros>
    <email>mgarciadegodos@egibide.org</email>
    <web>www.egibide.org</web>
    <compania>Egibide</compania>
</agenda>
