=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Personas/personas.dtd
<!ELEMENT personas (persona)+>
<!ELEMENT persona (nombre, email+, parentesco?)>

        <!ELEMENT nombre (#PCDATA)>
        <!ATTLIST nombre
                dni ID #REQUIRED
                edad CDATA #IMPLIED
                sexo (H|M) #REQUIRED>

        <!ELEMENT email (#PCDATA)>
        <!ELEMENT parentesco EMPTY>

        <!ATTLIST parentesco
                padre_de IDREF #IMPLIED
                hermano_de IDREF #IMPLIED>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Personas/personas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE personas SYSTEM "personas.dtd">

<personas>
    <persona>
        <nombre dni="_123456M" edad="50" sexo="H">
            Jose Luis
        </nombre>
        <email>jlg@gmail.com</email>
        <parentesco padre_de="_2345J"/>
    </persona>
    <persona>
        <nombre dni="_2345J" edad="17" sexo="M">
            Mar√≠a
        </nombre>
        <email>mgg@gmail.com</email>
    </persona>
    <persona>
        <nombre dni="_54785F" sexo="H">
            Pedro
        </nombre>
        <email>pgg@gmail.com</email>
        <parentesco hermano_de="_2345J"/>
    </persona>
</personas>
