=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Universidad/8.dtd
<!ELEMENT universidad (alumnos, profesores, asignaturas)+>

    <!ELEMENT alumnos (alumno)+>
        <!ELEMENT alumno (datos, matricula+)>
            <!ELEMENT matricula (asignatura, nota)>
            <!ELEMENT nota EMPTY>

    <!ELEMENT profesores (profesor)+>
        <!ELEMENT profesor (datos, despacho, horariosTutorias+, asignatura+)>
            <!ELEMENT despacho (#PCDATA)>
            <!ELEMENT horariosTutorias (#PCDATA)>

    <!ELEMENT asignaturas (asignatura)+>
        <!ELEMENT asignatura (creditos, carrera)>
            <!ATTLIST asignatura
                    codigo ID #REQUIRED>
            <!ELEMENT creditos (#PCDATA)>
            <!ELEMENT carrera (#PCDATA)>

    <!ELEMENT datos (dni|pasaporte, nombreCompleto, fechNac, infoContacto*)>
        <!ELEMENT dni EMPTY>
            <!ATTLIST dni ID #REQUIRED>
        <!ELEMENT pasaporte (paisProcedencia)>
            <!ELEMENT paisProcedencia (#PCDATA)>
            <!ATTLIST pasaporte
                        cod ID #REQUIRED>
        <!ELEMENT nombreCompleto (#PCDATA)>
        <!ELEMENT fechNac (#PCDATA)>
        <!ELEMENT infoContacto (#PCDATA)>
            <!ATTLIST infoContacto
                    tipo (correo|mail|telefono) #REQUIRED>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Soluciones/Universidad/Universidad.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE universidad SYSTEM "8.dtd">

<universidad>
    <alumnos>
        <alumno>
            <datos>
                <
            </datos>
            <matricula>
                <asignatura codigo="">
                    <creditos></creditos>
                    <carrera></carrera>
                </asignatura>
                <nota/>
            </matricula>
        </alumno>
    </alumnos>
    <profesores>
        <profesor>
            <datos>
                <
            </datos>
            <despacho></despacho>
            <horariosTutorias></horariosTutorias>
            <asignatura codigo="">
                <creditos></creditos>
                <carrera></carrera>
            </asignatura>
        </profesor>
    </profesores>
    <asignaturas>
        <asignatura codigo="">
            <creditos></creditos>
            <carrera></carrera>
        </asignatura>
    </asignaturas>
</universidad>
