=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Pedido/Pedido.dtd
<!ELEMENT compras (fecha, cliente, pedido, direcciones)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT cliente (#PCDATA)>
    <!ELEMENT pedido (cantidad, precio)+>
        <!ELEMENT cantidad (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
    <!ELEMENT direcciones (CP,direccion)>
        <!ELEMENT CP (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/DTD/Pedido/Pedido.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE compras SYSTEM "Pedido.dtd">
<compras>
    <fecha></fecha>
    <cliente></cliente>
    <pedido>
        <cantidad></cantidad>
        <precio></precio>
    </pedido>
    <direcciones>
        <CP></CP>
        <direccion></direccion>
    </direcciones>
</compras>
