=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Simulacro Examen/Enunciado/Ejercicio1.dtd
<!ELEMENT ticket (evento, fecha, hora, nivel, seccion, IDventa, apellidos, nombre, edad, precio)>
    <!ELEMENT evento (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT hora (#PCDATA)>
    <!ELEMENT nivel (#PCDATA)>
    <!ELEMENT seccion (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT IDventa (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>

=== Barraguesh/2GDAW/1GDAW/LMSGI/XML/XSD/Simulacro Examen/Enunciado/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE ticket SYSTEM "Ejercicio1.dtd">-->
<ticket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio1.xsd">
    <eventototal id="561565">
        <evento>Jackson Hole Rodeo</evento>
        <fecha>8/7/2013</fecha>
        <hora>8:00PM</hora>
        <nivel>Covered</nivel>
        <seccion>General Admission</seccion>
        <apellidos>Sarasola</apellidos>
        <nombre>Ion</nombre>
        <edad>Adulto</edad>
        <precio>25$</precio>
    </eventototal>
</ticket>
